### PR TITLE
mermaid demo

### PR DESCRIPTION
**Pull request by joaohf**
This is how it looks like:

demo_mermaid

See https://github.com/nitrogen/nitrogen_core/issues/99 for additional details

### CODE REVIEW

**Comment by choptastic** [comment]
Looks great so far.  When you've updated it for dynamic updates, I'd love to see if you could add a 3rd option for user-specified that live-updates the graph on the page, maybe one option demonstrating updating without a postback, and one with a postback.  What do you think?

**Comment by joaohf** [comment]
I totally agree.

See below the second demo. I'm preparing the last one.

Screenshot_2020-04-07_23-51-09

**Comment by joaohf** [comment]
Here is a third demo showing how to update a graph using async comet.

image

**Comment by choptastic** [comment]
I haven't commented on this, but once I merge in the request into nitrogen_core, I'll merge this in as well. This is great stuff! Kudos, man!

**Pull request merged**
